version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu

hooks:
  AfterInstall:
   - location: /home/ubuntu/scripts/afterInstall.sh
     timeout: 6000
     runas: ubuntu
  ApplicationStart:
   - location: /home/ubuntu/scripts/applicationStart.sh
     timeout: 6000
     runas: ubuntu