version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu

hooks:
  BeforeInstall:
  - location: scripts/beforeInstall.sh
    timeout: 6000
    runas: root
  AfterInstall:
   - location: scripts/afterInstall.sh
     timeout: 6000
     runas: root
  ApplicationStart:
   - location: scripts/applicationStart.sh
     timeout: 6000
     runas: root