---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            echo "Hello World"


workflows:
  version: 2
  pr-check-workflow:
    jobs:
      - pr_check